import type { Metadata } from "next";
import "./globals.css";
import logo from "../assets/logos/Logo.svg";

export const metadata: Metadata = {
  title: "Findtrend",
  description: "Generated by create next app",
  icons: logo,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-display@400,700,500,600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-clash-display">{children}</body>
    </html>
  );
}
